#! /bin/bash


count=0;
j=1;
for i in `cut -f1,9 -d' ' $1 | awk -F' ' '$2~"^3"' | uniq -cf1 | sort | cut -f3 -d' ' | tail -r -10 `
do 
  count=$((count+i))
done

for i in `cut -f1,9 -d' ' $1 | awk -F' ' '$2~"^3"' | uniq -cf1 | sort -n | tail -r -"10" | awk '{print $2 " " $1}'`
do
  if [[ $i =~ ^[0-9]+$ ]]; then
    printf "$i - $(echo "scale=2; $i / $count * 100" | bc)%% \n" ;
  else printf "$j. $i - "; j=$((j+1)); fi
done


